### ISSUE TITLE
Migrate Existing Issues from DynamoCore

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/DynamoWishlist#1]
@Amoursol  It would be great to move these [wishlist items](https://github.com/DynamoDS/Dynamo/labels/wishlist), to this repo with [this method](https://help.github.com/en/github/managing-your-work-on-github/transferring-an-issue-to-another-repository). We did this a while back for the DynamoRevit repo and it worked pretty awesome.

**Comment by Amoursol** [comment]
That's the plan man 😁 Thanks for the link... saves me looking!

**Comment by Amoursol** [comment]
This is done now @johnpierson !
