### ISSUE TITLE
Wiki Enhancement: How to write messages in the Dynamo Console

### ISSUE THREAD

**Issue by redinkinc** [DynamoDS/DynamoWishlist#105]
Can you please add a new entry in your wiki where you describe how to write in the console? would be nice to visualize some states of costum .dll's.
Thanks, Fabian

**Comment by Amoursol** [comment]
We are adding a new `DynamoPrint()` function to the Python node that allows you to print things to the Dynamo Console in our current Python upgrade project.

**Comment by Amoursol** [comment]
This is now in product in Dynamo 2.8: https://dynamobim.org/dynamo-core-2-8-release/
