### ISSUE TITLE
Wish: Control of Python Print destination

### ISSUE THREAD

**Issue by nreifenstein** [DynamoDS/DynamoWishlist#110]
It would be nice to be able to monitor the python node through intermittent "print" statements - for diagnostics and debugging  - keeping them separate from OUT. Essentially this is redirecting "stdout" to somewhere, perhaps the dynamo console, the node's message banner, or a separate "outie".

**Comment by Amoursol** [comment]
We are currently working on a project during our `CPython3 upgrade project` to enable the `print()` function to work within Dynamo. Watch this space!

**Comment by Amoursol** [comment]
This feature is now in product here: https://github.com/DynamoDS/Dynamo/pull/10924 and will surface itself in Dynamo 2.8. It enables the use of print to the Dynamo console in a non-logging format. 

Note: Finalizing work is being done to support the `print()` as user feature that calls the `DynamoPrint()` function in the back-end. This will enable more transferability between Python 3 content in and out of Dynamo.
