### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoWishlist#112]
Also, one more thing that I have noticed about the Package Manager earlier today. When uploaded nodes or published a version of a package from let's say Dynamo 0.8.1 and then because of instability reverted to Dynamo 0.8.0, if you try to upload a new version of that package from the now earlier version of Dynamo it will show a warning. You can ignore the warning, but the problem is that a new warning will pop up for every node that was added to the package from a future version. It's not a huge issue, more like a functionality enhancement. It would be nice to be able to just OK all of the nodes at once instead of clicking ok for every single one of them. @pboyer

**Comment by Amoursol** [comment]
@ksobon This was tested internally and not reproducible in latest builds. Closing for now, but please do reopen if you are still experiencing this issue.

**Comment by ksobon** [comment]
@Amoursol yeah, this issue is 8 years old. If it was a kid, it would be in a second grade. 😜

**Comment by Amoursol** [comment]
Hahaha... truth 🤣
