### ISSUE TITLE
PolyCurve.ByJoinedCurves throws an error when input contains multiple "loops"

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoWishlist#127]
This is less of a bug, but rather a request. It would be nice to have a JoinCurves() method similar to one in rhinocommon that is capable of taking unsorted input of curves and sorting them into closed loops/joined segments given some tolerance for max distance between curves. 
Right now it throws an error referring to multiple "wires". @hlp @kronz @pboyer 

thank you!

**Comment by aparajit-pratap** [comment]
See the latest `PolyCurve.ByGroupedCurves` node.
