### ISSUE TITLE
Excel Export AsString

### ISSUE THREAD

**Issue by BenBarfoot** [DynamoDS/DynamoWishlist#13]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## Dynamo version

Dynamo 2.0.1.5055

## Operating system

Window 10

## What did you do? 

Dynamo Script
![image](https://user-images.githubusercontent.com/49448380/55813200-4f3dbc00-5ae4-11e9-88a7-e4ebe08d203f.png)

## What did you expect to see?

Excel Export
![image](https://user-images.githubusercontent.com/49448380/55813292-71373e80-5ae4-11e9-9d27-575285e9ac2c.png)

## What did you see instead?

Excel Export
![image](https://user-images.githubusercontent.com/49448380/55812992-e5251700-5ae3-11e9-851a-262aee8356c6.png)

## Solution

Within the Exporting Node make it have an extra field that will enable the Export to convert the cells to Text shown in the images above. This field could look like the "AsString" like the Importing Node.

**Comment by QilongTang** [comment]
@BenBarfoot This will be available starting from Dynamo 2.11.0. Closing and cheers,

![image](https://user-images.githubusercontent.com/3942418/102256567-8b403b80-3ed9-11eb-8ab4-0ac42bd122d5.png)

**Comment by Amoursol** [comment]
This is now in product: https://github.com/DynamoDS/Dynamo/pull/11291
