### ISSUE TITLE
Wish: Small UI improvement for tabs

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#130]
In the file name tabs, Dynamo indicates whether a file has unsaved changes by placing an asterisk behind the file name. For files with long file names, however, the symbol will not be displayed as the name is cut off after a certain number of letters. Maybe it would be a good idea to have the asterisk displayed _in front of_ the file name instead.

**Comment by saintentropy** [comment]
This was fixed with the Dynamo visual refresh
![image](https://github.com/DynamoDS/DynamoWishlist/assets/2145751/fe7af6c4-2707-4220-ac63-3f9f971bc943)
