### ISSUE TITLE
Cannot copy to clipboard from preview bubble anymore

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#132]
In 0.6.3, I used to be able to select everything that was displayed in the preview bubble and copy it to the clipboard. This doesn't seem to be possible in 0.7 anymore. Any chance for a comeback?

**Comment by Amoursol** [comment]
This is now in Dynamo 😄  - refer to PR: https://github.com/DynamoDS/Dynamo/pull/11292
