### ISSUE TITLE
improvement: ability to see spaces and tabs in python editor

### ISSUE THREAD

**Issue by mjkkirschner** [DynamoDS/DynamoWishlist#137]
very frequently copy/pasted code gives errors in the python nodes as white space is important and sometimes formatting is lost.

![screen shot 2014-01-23 at 11 24 39 pm](https://f.cloud.github.com/assets/508936/1992065/7a5320b2-84af-11e3-8f59-0bdb8ec07a1c.png)

sublime as an example

**Comment by Amoursol** [comment]
This feature is now in product and will release with Dynamo 2.8: https://github.com/DynamoDS/Dynamo/pull/10948
