### ISSUE TITLE
[Feature Request] Python - allow logging to dynamo console (Print to console)

### ISSUE THREAD

**Issue by kv2** [DynamoDS/DynamoWishlist#147]
Please make logging to dynamo console from within the python nodes. Currently, to debug long python scripts, I have to write to a file.

**Comment by Amoursol** [comment]
This Wishlist item is currently being tracked internally 😊  we hope to share something in the not-to-distant future on this!

**Comment by Amoursol** [comment]
This feature is now in product here: https://github.com/DynamoDS/Dynamo/pull/10924 and will surface itself in Dynamo 2.8! 

Note: Finalizing work is being done to support the `print()` as user feature that calls the `DynamoPrint()` function in the back-end. This will enable more transferability between Python 3 content in and out of Dynamo.
