### ISSUE TITLE
Print to Dynamo console from custom node

### ISSUE THREAD

**Issue by vryy** [DynamoDS/DynamoWishlist#151]
If this issue is with Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a bug report or improvement request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.
## Dynamo version

1.2.1.2737
## Operating system

Windows 10 anniversary
## What did you do?

I implemented a custom node in C# which does some computation. To debug the code I printed out some values to the console. However, DynamoSandbox (under View/Show Console), only the information from Dynamo kernel is printed. I'd like to request a new feature that allows for feeding the console from custom node.
## What did you expect to see?

(Fill in here)
## What did you see instead?

(Fill in here)

**Comment by Amoursol** [comment]
This is now in product as of Dynamo 2.8 - refer to: https://dynamobim.org/dynamo-core-2-8-release/
