### ISSUE TITLE
Allow users to toggle "Show Grid" when all 3D Background Previews are disabled

### ISSUE THREAD

**Issue by xdkaplan** [DynamoDS/DynamoWishlist#165]
## What improvement/feature would you like to see in Dynamo?

When the 3D Background is disabled in Dynamo, I would like to the ability to disable the Grid

When sharing graphs I feel the grid doens't add anything to the UI since there's no snapping. If anything, it reminds me that my nearly-horizontal wires aren't perfect

## How would you see this improvement/feature working? 

Under the View dropdown, I would rename "Background 3D Preview" to simply "Background Preview".
When both "Background Preview"s are disabled, I would allow the user to disable "Show Grid". It is currently grayed out.

## Please provide any sketch/mock-up or video of your requested improvement/feature
"Show Grid" Enabled/Disabled

![image (1)](https://user-images.githubusercontent.com/57241483/87462174-82230980-c5dd-11ea-96fa-909153d3c0b1.png)

**Comment by Amoursol** [comment]
@Dewb has this now been fixed in your PR?

**Comment by QilongTang** [comment]
@Amoursol Should be available now? Here is a gif and I think that is what @xdkaplan asked for:
![DisableShowGrid](https://user-images.githubusercontent.com/3942418/88198446-b1ef9400-cc11-11ea-901e-792e7c1beded.gif)

**Comment by Amoursol** [comment]
Yes, this is indeed fixed and is available when Dynamo 2.8 ships 💪
