### ISSUE TITLE
Python script editor - Zoom Text

### ISSUE THREAD

**Issue by osdenprog** [DynamoDS/DynamoWishlist#178]
## What improvement/feature would you like to see in Dynamo?

Python script editor, as it’s simple but much helpful, why still not integrate the option of zooming to text with the python editor into the Dynamo.
I have explained about this feature into the forum under this link:
https://forum.dynamobim.com/t/dynamo-python-editor/56670  

![8b3948dd5ddf6f0513f7083dbfb4fb17fc8c10ee](https://user-images.githubusercontent.com/62112113/97572601-357b0700-19f1-11eb-998b-3442a1cc544b.jpeg)

**Comment by Amoursol** [comment]
@osdenprog this is actively under development now, please refer to https://github.com/DynamoDS/Dynamo/pull/13427

**Comment by avidit** [comment]
fixed by https://github.com/DynamoDS/Dynamo/pull/13427
