### ISSUE TITLE
python 

### ISSUE THREAD

**Issue by epeter-** [DynamoDS/DynamoWishlist#179]
maybe it is time to allow users to adopt the python editor environment.
i.e. it is almost impossible to read a hyperlink embedded in the code (black background and darkblue text color)
i am currently working ion hires screens. the text size seems to be much to small.

**Comment by QilongTang** [comment]
@mjkkirschner I am all for it. Logged and tracked in https://jira.autodesk.com/browse/DYN-3265.

**Comment by epeter-** [comment]
@mjkkirschner michael the use of the pythonFromString node is only feasible when there is just one piece of python code in a dynamo graph.
if you use some distributed snippets of python code in a graph you might get drowned in a sea of .py files. this making your graph very difficult to maintain

**Comment by QilongTang** [comment]
@epeter- Understood. My question is that is this one duplicate with https://github.com/DynamoDS/DynamoWishlist/issues/178? What do you imagine the difference of UX is?

**Comment by Thomas84** [comment]
@QilongTang it is a duplicate with https://github.com/DynamoDS/DynamoWishlist/issues/28 but this thread mentions 4K and #28 does not.

**Comment by avidit** [comment]
fixed by [#13732](https://github.com/DynamoDS/Dynamo/pull/13732)
