### ISSUE TITLE
Feature Request for Dynamo 2.13.x+ - Shift and Drag Items Out of Group

### ISSUE THREAD

**Issue by johnpierson** [DynamoDS/DynamoWishlist#206]
## Dynamo version
2.13.x

## Operating system
Windows 95

## What did you do? 
Adding nodes to groups with click-drag is awesome. I would also love to remove from groups with a shift + drag out of the group. 🙂

**Comment by Amoursol** [comment]
See PR from @johnpierson here https://github.com/DynamoDS/Dynamo/pull/12571 to solve @johnpierson's Wishlist item 😉

**Comment by johnpierson** [comment]
Me opening wishlist items for my own Prs [](https://wompampsupport.azureedge.net/fetchimage?siteId=7575&v=2&jpgQuality=100&width=700&url=https%3A%2F%2Fi.kym-cdn.com%2Fphotos%2Fimages%2Fnewsfeed%2F001%2F510%2F176%2Fe33.jpg)

**Comment by Amoursol** [comment]
This awesome PR will be inside Dynamo 2.14! 💪
