### ISSUE TITLE
Hotkey F1 for the Extended Node Help

### ISSUE THREAD

**Issue by Thomas84** [DynamoDS/DynamoWishlist#216]
## What improvement/feature would you like to see in Dynamo?

In addition to the Help Button in the node context menu, it should be possible to press F1 to open the Extended Help of a node.

## How would you see this improvement/feature working? 

If single node is selected and the key F1 is pressed, the extended help pops up

## Please provide any sketch/mock-up or video of your requested improvement/feature

![images](https://user-images.githubusercontent.com/5624034/165142353-1406ee17-1790-4813-affc-7612bc0b3726.jpg)

🤓

**Comment by avidit** [comment]
Addressed by: https://github.com/DynamoDS/Dynamo/pull/12894
More info: https://github.com/DynamoDS/Dynamo/wiki/Dynamo-Keyboard-Shortcuts

**Comment by zeusongit** [comment]
This feature will be available in the next Dynamo release.
