### ISSUE TITLE
Improvement way to resolve NuGet for collaborate open source

### ISSUE THREAD

**Issue by chuongmep** [DynamoDS/DynamoWishlist#230]
If this is an issue for Dynamo Core, please submit your issue on the [Dynamo Core issues page](https://github.com/DynamoDS/Dynamo/issues) or if this is an issue for Dynamo for Revit, please post your issue on the [Dynamo for Revit Issues page](https://github.com/DynamoDS/DynamoRevit/issues).

If this issue is **not** a Wishlist request, please check the [Dynamo forum](https://forum.dynamobim.com/), and start a thread there to discuss your issue.

## What improvement/feature would you like to see in Dynamo?

Should be implement nuget allow developer can colaborate
![image](https://user-images.githubusercontent.com/31106432/201691714-2453b71b-a210-4c1c-bfaf-0bb629f42e22.png)

## How would you see this improvement/feature working? 

Open Project Dynamo Revit don't have any problem with some package resolve, revit api can accept, In fact, many developers were frustrated when opening this project. If this continues, this is a big limit for developers who want to collaborate with open source.

## Please provide any sketch/mock-up or video of your requested improvement/feature

(Fill in here)

**Comment by mjkkirschner** [comment]
Hi @chuongmep - is there a particular package you found would not download?

**Comment by wangyangshi** [comment]
![image](https://user-images.githubusercontent.com/62596335/201841883-5c9e4d22-11c1-45fe-a109-fd6ad7cf0051.png)
this is my local display,
Build it once, these red lines will disappear.

**Comment by QilongTang** [comment]
@wangyangshi Is D4R still depending on a local install of Revit depending on the branch? If yes, can we document it somehow?

**Comment by wangyangshi** [comment]
Do you mean RevitAPI? 
for released branch of D4R, it depends on a fixed version of RevitAPI (like 23.0.0.261 in 2023)
for master branch of D4R, it depends on the latest version of RevitAPI (like 24.0.0.315)

**Comment by wangyangshi** [comment]
@QilongTang RevitAPI.dll and RevitAPIUI.dll are installed with Revit, user can search it in his computer,  their path are same with revit.exe.
for other versions they can find it on nuget or somewhere I think.
do we need to add this explanation in d4r README?

**Comment by QilongTang** [comment]
> @QilongTang RevitAPI.dll and RevitAPIUI.dll are installed with Revit, user can search it in his computer, their path are same with revit.exe. for other versions they can find it on nuget or somewhere I think. do we need to add this explanation in d4r README?

Please do, as a former developer on this repo, I understand how to find them but other developers may not, and admitedly it is hard to figure out which RevitAPI.dll is required for which release branch/master

**Comment by wangyangshi** [comment]
OK, I will add these info in D4R README

**Comment by chuongmep** [comment]
Thanks for all, I will check this is problem resolved now.
