### ISSUE TITLE
[Feature Request] Save Geometry Working Range Settings

### ISSUE THREAD

**Issue by sougenbread** [DynamoDS/DynamoWishlist#40]
Just a simple request to avoid having to reset the setting to 'Large' everytime I create a new graph.
I work in metric so this is necessary.

Thank you very much!

**Comment by Amoursol** [comment]
Tracked internally on JIRA: https://jira.autodesk.com/browse/DYN-4733

**Comment by avidit** [comment]
- https://github.com/DynamoDS/Dynamo/pull/12876

**Comment by Amoursol** [comment]
This is now inside of Dynamo from Dynamo 2.15 onwards 🙌
