### ISSUE TITLE
Feature request: Expose method to query current Dynamo workspace path using DesignScript/Python

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#46]
## Dynamo version

Any

## Operating system

Windows 7

## Feature Request

I'd like to have access to the full path of the currently loaded workspace. The only way I know of achieving this presently is to first save the graph in Dynamo and only then run it and have it examine the Dynamo log.

Use case: I'd like to look for other files in the same folder as the current Dynamo workpace.

**Comment by Amoursol** [comment]
Hello @andydandy74,

This is possible in Python now (Apparently has been for a bit so apologies for not passing this on!):

`import clr
clr.AddReference('DynamoServices')
from Dynamo.Events import *

OUT = ExecutionEvents.ActiveSession.CurrentWorkspacePath`
