### ISSUE TITLE
go to label - node

### ISSUE THREAD

**Issue by m-danm** [DynamoDS/DynamoWishlist#5]
Can you please add a "Go to" node to send data to a specific location in the script?

wires are nice but scripts need to be decluttered.

**Comment by Amoursol** [comment]
@m-danm From Dynamo 2.13 onwards you can now "Hide wires" if you wish. You can also use custom nodes from the "Springs" package to do this. 

![image](https://user-images.githubusercontent.com/12857357/160149224-58d9136a-68b0-45d0-9a3d-311b70c2a308.png)
