### ISSUE TITLE
List.Shuffle shuffles nested lists incorrectly

### ISSUE THREAD

**Issue by dimven** [DynamoDS/DynamoWishlist#54]
## Dynamo version

ever since 0.82:
http://dynamobim.org/forums/topic/random-list-of-lists/

## Operating system

Windows 7

## What did you do? 

Ran some nested lists through a list-shuffle node

## What did you expect to see?

Uniquely shuffled sub-lists

## What did you see instead?

Identically shuffled lists:

![revit_2017-04-20_09-25-25](https://cloud.githubusercontent.com/assets/7148394/25209235/4832e346-25ac-11e7-89af-e6a2f1a30019.png)

This was reported previously and ignored:
https://github.com/DynamoDS/Dynamo/issues/5977

**Comment by Amoursol** [comment]
This has now been fixed in Dynamo 2.10: https://dynamobim.org/dynamo-core-2-10-release/
