### ISSUE TITLE
publishing package online after it was published locally

### ISSUE THREAD

**Issue by ksobon** [DynamoDS/DynamoWishlist#68]
## Dynamo version

stable 1.1
## Operating system

win 10
## What did you do?

tried publishing a package (online)
## What did you expect to see?

a package get published online
## What did you see instead?

it failed with an error saying that package doesn't exist or something like that. 

I was able to publish it but only after i deleted the local version of my package and published a new package online first. I think the problem was that i had this package published locally and then I tried to publish online.

**Comment by Amoursol** [comment]
We have tested and validated this as working now, as per the following steps. Should this not be the case please do re-open with more information:

> After publishing a package locally, go to **Preferences >  Package Manager**, click on the overflow menu for the package and click on **Publish**... to publish it online. 
If you click on **Publish Version**... it will fail as it is not present on the online package database yet.
