### ISSUE TITLE
Wish: Show incoming values in input tooltip

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#69]
## Dynamo version

Any
## Operating system

Any
## Feature request

When hovering over the input port of a node in a graph that has already been executed it would often be helpful to be able to see the incoming data (in addition to the existing content of the node input port tooltip), especially in larger graphs where the node that created that data might be located in a remote part of the graph.

**Comment by Amoursol** [comment]
@andydandy74 a variant of this has now been introduced into Dynamo 2.13. By hovering on any wire, you get a "Data preview" and can also attach a watch node through this wire. 

![image](https://user-images.githubusercontent.com/12857357/160145717-ac248354-5c27-46b8-93a4-1da67aece95d.png)
