### ISSUE TITLE
Wish: Access Dynamo's Package Paths from Python

### ISSUE THREAD

**Issue by mostaphaRoudsari** [DynamoDS/DynamoWishlist#71]
Following up from [this discussion](https://forum.dynamobim.com/t/access-dynamos-package-paths-from-python/4575?u=mostapha) on the forum.

I'm looking for a call from inside python node to access package path(s)? It will save me an other developers who are loading the libraries from package folder a lot of duplicated code and also ensures that we can have access to the libraries even if the user installs them in a custom folder.

![](https://cdn-business.discourse.org/uploads/dynamobim/original/2X/c/c265f7c4f1b15f39c04bcabf8a98b12d42df000b.png)

cc: @mjkkirschner
labels: wish, python

**Comment by mjkkirschner** [comment]
Please see related PR.

**Comment by mostaphaRoudsari** [comment]
@mjkkirschner, thanks. Do we know from which version of Dynamo this will be available?

**Comment by mjkkirschner** [comment]
as of now, this code has been merged to trunk which is currently 2.8.

**Comment by Amoursol** [comment]
Hello @mostaphaRoudsari - Have you had a chance to check this in a daily build?

**Comment by mikkelvangsgaard** [comment]
Hi, any updates on this?

thanks

**Comment by Amoursol** [comment]
Hello @mikkelvangsgaard - This is now part of `Dynamo 2.8` 😄

**Comment by mikkelvangsgaard** [comment]
Great! Thank you @Amoursol
