### ISSUE TITLE
Improvement: Groups within groups

### ISSUE THREAD

**Issue by ThomasMahon** [DynamoDS/DynamoWishlist#80]
## Dynamo version

1.0.0
## Operating system

Win 10
## Improvement Suggestion:

Group nodes within other groups - would really help to keep graphs better organised and demystify data flow or important 'sub-groups' of nodes. This request was also made by a recent user group I was training.

**Comment by Amoursol** [comment]
@ThomasMahon this is now a feature of Dynamo 2.13!
