### ISSUE TITLE
Running pandas from Dynamo Python Script

### ISSUE THREAD

**Issue by mariamingallonMM** [DynamoDS/DynamoWishlist#9]
Hello, 

It would be great to use pandas, numpy and many others from the Python Script editor directly. Please share any developments on this front. 

Thanks
Maria

**Comment by Amoursol** [comment]
This is now possible with our latest release, `Dynamo 2.7` and the steps to get there are illustrated in this post: https://forum.dynamobim.com/t/new-feature-preview-python-3-support-issue-thread/51649/48 

(Note: We are going to make a better experience in the on-going Python upgrade work, but this gets it into your hands faster!)
