### ISSUE TITLE
Wish: Remove A360 login for local package publishing

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#92]
## Dynamo version

0.9.0
## Operating system

Windows 7
## What did you do?

Selected a custom node and chose "Publish selected node" in the context menu
## What did you expect to see?

The Publish Package dialogue
## What did you see instead?

The A360 login prompt. For publishing a package locally this does not seem necessary. Maybe it would make more sense to show the prompt only if the "Publish online" option is selected. Also, not having to constrain a local package to a single A360 account would facilitate having multiple package maintainers (until that is a supported feature).

**Comment by Amoursol** [comment]
This should become redundant with our new Authentication in Core work being done. FYI @avidit @QilongTang

**Comment by reddyashish** [comment]
User should now be able to publish a package version from Dynamo sandbox after the user is logged into Dynamo.
