### ISSUE TITLE
Wish: Extend capabilities of Range node

### ISSUE THREAD

**Issue by andydandy74** [DynamoDS/DynamoWishlist#96]
Recently, the `Number Range` node was turned into the `Range` node (#5234) that can now process alphabetical lists as well. Great!
I would like to suggest two improvements:
1. Set a default value of 1 for the `step` input as that is the value most typically used with this node.
2. Do not stop at 26 letters, e.g. a range of 28 would then yield the following sequence: 
a, b, c, ..., x, y, z, aa, ab (basically like column numbering in Excel)
Also, it would be great if the same were possible with list syntax in code blocks.

**Comment by Amoursol** [comment]
@andydandy74 - Default value is still one. Other result is achievable via DesignScript and the Sequence node :) 

![image](https://user-images.githubusercontent.com/12857357/78154034-c3662380-7409-11ea-9610-88cf586b1dfa.png)

**Comment by maxcubcru88** [comment]
If the amount value in the sequence is 500, why the list contains only 426 items? It blows my mind!

**Comment by Amoursol** [comment]
Hi @maxcubcru88 this is because that is the total amount of characters that exist within the Sequence :) We are simply stating "Start at "A" and go until 500, or until you run out. In this case, we run out before we get to 500.

**Comment by maxcubcru88** [comment]
Hi @Amoursol 

See snapshot below, if we increase the amount value, the number of items increase too...  

![Capture](https://user-images.githubusercontent.com/91635092/135717400-9a0f71e8-b03c-47df-adce-4ec34989d179.JPG)

**Comment by Amoursol** [comment]
Ah... so weird. A bug indeed then! Thanks for the clarification @maxcubcru88 🙏  

Any ideas what is happening here @aparajit-pratap @mjkkirschner ?

**Comment by mjkkirschner** [comment]
my guess is this:
https://github.com/DynamoDS/Dynamo/blob/f9c7691d8de0d264566bea1b29cc9719dc567547/src/Engine/ProtoCore/Lang/BuiltInFunctionEndPoint.cs#L1388


this sequence start is based on the asci code of the letter - and incrementing it, but the loop will skip any values that are not letters.
